services:
  #######################################################
  #  Backend (.NET 9)                                   #
  #######################################################
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "5000:5000"                    # host:container
    # healthcheck:                       # проверяем доступность API
    #   test: ["CMD", "curl", "-f", "http://localhost:5000/healthz"]
    #   interval: 30s
    #   timeout: 3s
    #   retries: 5

  #######################################################
  #  Frontend (React + TS)                              #
  #######################################################
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend                          # ждём пока API взлетит
    environment:
      # адрес API прокидываем в фронт (vite читает из import.meta.env)
      VITE_API_BASE_URL: http://backend:5000
    ports:
      - "80:80"                          # React статика