services:
  #######################################################
  #  Backend (.NET 9)                                   #
  #######################################################
  backend:
    image: dielectrici/pet1-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports: [5000:5000]
    networks: [petnet]

  #######################################################
  #  Frontend (React + TS)                              #
  #######################################################
  frontend:
    image: dielectrici/pet1-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # ⬇⬇⬇  Прокидываем URL API прям в стадию build,
      # чтоб Vite «зашил» его в JavaScript-бандл.
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://backend:5000}
    depends_on: [backend]
    ports: [3000:80]              # host:container
    networks: [petnet]
    
networks:
  petnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
          gateway: 172.30.0.1
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "false"