services:
  ############################
  #      Fluent-bit          #
  ############################
  fluent-bit:
    image: cr.fluentbit.io/fluent/fluent-bit:3.0
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
    networks: [ petnet ]
    depends_on:
      backend:
          condition: service_healthy
    command: -c /fluent-bit/etc/fluent-bit.conf
  
  ############################
  #          Loki            #
  ############################
  loki:
    image: grafana/loki:latest
    ports: [ 3100:3100 ]
    command: -config.file=/etc/loki/local-config.yaml
    networks: [ petnet ]
  
  ############################
  #       Grafana            #
  ############################
  grafana:
    env_file: .env
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    networks: [ petnet ]
    depends_on: [ loki ]
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
  
  ############################
  #  Database (PostgreSQL)   #
  ############################
  db:
    env_file: .env
    image: postgres:16-alpine
    volumes: [ db-data:/var/lib/postgresql/data ]
    ports: [ 5432:5432 ]
    networks: [ petnet ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
  
  ############################
  #    Backend (.NET 9)      #
  ############################
  backend:
    env_file: .env
    # image: dielectrici/pet1-backend:latest
    build:
      context: ./backend
    ports: [ 5000:5000 ]
    networks: [ petnet ]
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:5000/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  ############################
  #  Frontend (React + TS)   #
  ############################
  frontend:
    # image: dielectrici/pet1-frontend:latest
    build:
      context: ./frontend
    ports: [ 3000:80 ]              # host:container
    networks: [ petnet ]
    depends_on:
      backend:
        condition: service_healthy

networks:
  petnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
          gateway: 172.30.0.1
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "false"

volumes:
  db-data:
  grafana-data:
