services:
  #######################################################
  #  Backend (.NET 9)                                   #
  #######################################################
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports: [5000:5000]
    networks: [petnet]

  #######################################################
  #  Frontend (React + TS)                              #
  #######################################################
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # ⬇⬇⬇  Прокидываем URL API прям в стадию build,
      # чтоб Vite «зашил» его в JavaScript-бандл.
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://backend:5000}
    depends_on: [backend]
    ports: [3000:80]              # host:container
    networks: [petnet]
    
networks:
  petnet:
    driver: bridge