# fluent-bit.yaml
service:
  flush: 5
  log_level: info
  parsers_file: /fluent-bit/etc/parsers.yml

pipeline:
  inputs:
    - name: tail
      path:
        - /var/lib/docker/containers/*/*.log 
      parser: docker
  filters:
    - name: parser
      match: "*"
      key_name: log
      parser: logfmt
      reserve_data: true

  outputs:
    - name: loki
      match: "*"
      host: loki
      port: 3100