# fluent-bit.yaml
service:

  flush: 5
  log_level: info
  parsers_file: /fluent-bit/etc/parsers.yml

pipeline:

  inputs: 
    - name: forward
      listen: 0.0.0.0
      port: 24224
  filters:
    - name: modify
      match: "*"
      Rename:
        - com.docker.compose.service service_name
        - com.docker.compose.project project_name
  outputs:
    - name: loki
      match: "*"
      host: loki
      port: 3100
      labels: service_name=$service_name, project_name=$project_name
      remove_keys: container_id, source, container_name
      # line_format: json