# fluent-bit.yaml
service:

  flush: 5
  log_level: info
  parsers_file: /fluent-bit/etc/parsers.yml

pipeline:

  inputs: 
    - name: forward
      listen: 0.0.0.0
      port: 24224

  filters:
    - name: modify
      match: "*"
      Rename:
        - com.docker.compose.service service_name
        - com.docker.compose.project project_name

    - name: parser
      match: "svc.*-backend-*"
      key_name: log
      parser: serilog_compact
      reserve_data: On

    - name: modify
      match: "svc.*-backend-*"
      Rename:
        - '@m message'
        - '@i event_id'
        - "@tr trace_id"
        - "@sp span_id"
        - RequestMethod method
        - RequestPath route
        - StatusCode status

    # # Если @l есть переименовываем в level
    # - name: modify
    #   match: "svc.*-backend-*"
    #   Condition: Key_Exists @l
    #   Rename:
    #     - '@l level'

    # # Если level отсутствует — выставляем Information
    # - name: modify
    #   match: "svc.*-backend-*"
    #   Condition: Key_Does_Not_Exist level
    #   Set: level Information


  outputs:
    - name: loki
      match: "*"
      host: loki
      port: 3100
      labels: service_name=$service_name, project_name=$project_name, level=$level, status=$status, method=$method
      remove_keys: container_id, source, container_name
      
    - name: stdout
      match: "*"