# fluent-bit.yaml
service:

  flush: 5
  log_level: info
  parsers_file: /fluent-bit/etc/parsers.yml

pipeline:

  inputs: 
    - name: forward
      listen: 0.0.0.0
      port: 24224

  filters:
    - name: modify
      match: "*"
      Rename:
        - com.docker.compose.service service_name
        - com.docker.compose.project project_name
    
    ########################
    #  Backend (Serilog)   #
    ########################
    - name: parser
      match: "svc.*-backend-*"
      key_name: log
      parser: serilog_compact
      reserve_data: On

    - name: modify
      match: "svc.*-backend-*"
      Rename:
        - '@m message'
        - '@i event_id'
        - "@tr trace_id"
        - "@sp span_id"
        - RequestMethod method
        - RequestPath route
        - StatusCode status

    ########################
    #    DB (Postgres)     #
    ########################
    - name: parser
      match: "svc.*-db-*"
      key_name: log
      parser: postgres_log
      reserve_data: On

    # Приводим уровень к общему полю level
    - name: modify
      match: "svc.*-db-*"
      Rename:
        - pg_level level

    ########################
    #    Frontend(Nginx)   #
    ########################
    - name: parser
      match: "svc.*-frontend-*"
      key_name: log
      parser: nginx
      reserve_data: On

    - name: modify
      match: "svc.*-frontend-*"
      Rename:
        - path route

    ########################
    #      Grafana         #
    ########################

    - name: parser
      match: "svc.*-grafana-*"
      key_name: log
      parser: logfmt
      reserve_data: On

    - name: modify
      match: "svc.*-grafana-*"
      Rename:
        - msg message

    ########################
    #      Loki            #
    ########################
    - name: parser
      match: "svc.*-loki-*"
      key_name: log
      parser: loki_parser
      reserve_data: On

    # Привести к единому message
    - name: modify
      match: "svc.*-loki-*"
      Rename:
        - msg message

    ########################
    #      Fluent Bit      #
    ########################
    - name: parser
      match: "svc.*-fluent-bit-*"
      key_name: log
      parser: fluentbit_internal
      reserve_data: On

  outputs:
    - name: loki
      match: "*"
      host: loki
      port: 3100
      labels: service_name=$service_name, project_name=$project_name, level=$level, status=$status, method=$method
      remove_keys: container_id, source, container_name
      
    # - name: stdout
    #   match: "*"